version: '3.9'

services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=gochelias
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test

    tasklab:
        container_name: tasklab
        restart: always
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - '3000:3000'
            - '3001:3001'
            - '4000:4000'
        volumes:
            - ./:/app/
            - /app/node_modules/
        links:
            - 'db'
